### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/reasonml#1]
Use this issue to track the work needed to launch. We have a launch guide that we'll keep up to date with changes here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

**Comment by stevejb71** [comment]
@kytrinyx We have a few students on the track already. Is there any way for maintainers to be able to see / review exercises without having to submit solutions?

**Comment by kytrinyx** [comment]
@stevejb71 Sorry, I'm catching up on about 6 weeks worth of notifications.

In the new site, you do not have to submit solutions, you just need to be a registered mentor for the track. That process starts at http://mentoring.exercism.io/

**Comment by tejasbubane** [comment]
I think we can close this and track launch in #17. Please reopen if required.
