### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/reasonml#169]
This repository's `main` branch currently does not pass all CI checks.
This makes detecting issues in PRs harder and might result in a broken track, and so is an important thing to fix.

The following CI workflows are currently failing:

https://github.com/exercism/reasonml/runs/3371776596

## Tracking

https://github.com/exercism/v3-launch/issues/55

**Comment by BNAndras** [comment]
Latest CI runs are passing.
