### ISSUE TITLE
Consider consistency for the exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/reasonml#2]
- Is there a style guide for ReasonML?
- Are these styles encouraged or enforced?
- Are there any conventions that we should adopt on this track for the sake of consistency?
- Can we enforce these?
- Is there a linter? Are there many? Should we use one?
- When you add a linter, edit the pull request template [link]
- Update the pull request template with checks that are appropriate for this track
- Is there a common convention for filenames? If not, what should our convention be?

Note that this is about the exercises (the test suites and code examples), not people's solutions.

**Comment by gabrielperales** [comment]
@kytrinyx ReasonML comes with [refmt](https://github.com/reasonml/reason-cli#optional-install-as-local-developer-tool), and that's the standard style, so it must be encouraged to keep consistency.

**Comment by kytrinyx** [comment]
Oh, that makes it easier.

I think the only question that I still have is what the filename conventions are or should be. If you have the answer to that I think it's probably safe to close this issue.

**Comment by gabrielperales** [comment]
I think @jaredly or @bsansouci will be pleased to help us answer those questions. They are very active ReasonML developers.

**Comment by jaredly** [comment]
Filename convention: in the reason community, `PascalCase.re` is the standard.

**Comment by kytrinyx** [comment]
Excellent. I'll leave this to you to decide whether you want to close now, or if you want to document this somewhere first.

**Comment by stevejb71** [comment]
I think we should document in the contributing markdown

**Comment by stevejb71** [comment]
I've updated the contributor markdown regarding refmt. I'll close this for now, reopen if anyone wants to implement an automated run of it.
