### ISSUE TITLE
Issue in raindrops raised by a student

### ISSUE THREAD

**Issue by stevejb71** [exercism/reasonml#55]
https://exercism.io/mentor/solutions/354b2cb95f7d4db6b19ed4026ef74336

**Comment by naartjie** [comment]
Hi, @stevejb71. Thanks, this is the one I raised I think. 

I made a PR for it #57.

I want to go through the other exercises, and check if there are any more dependency issues, like in #56. I'll open a separate issue.

@nickcernis thanks for the `--env=node` fix!
