### ISSUE TITLE
Upgrade bs-platform

### ISSUE THREAD

**Issue by tejasbubane** [exercism/reasonml#66]
Current `bs-platform` version we use is `3.1.5` but `v4` has released for a while. Update it to the latest version:

Things to be done:

1. Change version manually [here](https://github.com/exercism/reasonml/blob/master/package.json#L18) to the latest one on [npm](https://www.npmjs.com/package/bs-platform)
1. Run `npm install` so that `package-lock.json` is updated with the new version.
1. Run `make sync-package-files` so that package-files in all exercises get updated.
1. Run `make` to run all tests and make sure all is well.
1. Commit, push and create a PR 🎉

**Comment by ohana54** [comment]
On it
